### ISSUE TITLE
[BUG] Heel height default should vary based on the year of the house

### ISSUE THREAD

**Issue by ehwarren** [bluegrv/blue2k-issues#19]
For a house pre-1990 it should be 0.33ft
A list of default heel heights is still needed

**Comment by liam-butters** [comment]
Heel height should be set to 0.33ft for homes older than 1990, and 0.43ft for homes newer (and including) 1990.  This is per ERS Technical Procedures 3.5.3.3 (see image below).

![image](https://github.com/bluegrv/blue2k-issues/assets/139492023/e017711b-0f76-413a-bfcd-b35fdecbd0b7)

**Comment by ehwarren** [comment]
Fixed in 0.7.3

Should be noted that default heel heights are only applied when actually creating the ceiling component. If the year that the house was built is later modified, any existing ceilings will retain their original heel height.
