### ISSUE TITLE
[BUG] H2K errors due to ELA area = 0 and volume = 0 when not using Blue2K for blower door data entry[BUG]

### ISSUE THREAD

**Issue by liam-butters** [bluegrv/blue2k-issues#28]
**Describe the bug**
When outputting a H2K file, very frequently H2K throws a "the equivalent leakage area cannot be set to 0.  Please edit the ELA" error and a "the volume specified for this house is 0!  Please correct" error. 

**To Reproduce**
1. Generate H2K file without having entered any blower door data
2. Save or calculate file.

**Expected behavior**
Ideally this error would be avoided by setting the ELA and volume to 0.1 or something.  The values will have to be adjusted regardless, but it would avoid having the error come back.

**Comment by ehwarren** [comment]
This is a tough one...

I think I would like to leave this as is. If a user forgot to enter their data or accidentally left their ach or volume at 0, h2k should remind them that this hasn't been filled out when they go to save.

This will eventually be a part of the "Verify file" process in blue2k as well.
