### ISSUE TITLE
[BUG] When entering 1.5" of XPS for a foundation wall, the output into H2K was R28 batt

### ISSUE THREAD

**Issue by liam-butters** [bluegrv/blue2k-issues#35]
**Describe the bug**
When entering 1.5" of XPS for a foundation wall, the output into H2K was R28 batt

**To Reproduce**
1. Model basement
2. Add 1.5" of XPS to foundation walls
3. Output to H2K
4. Check insulation level on foundation wall.  My output is R28 batt.

**Expected behavior**
Should be 1.5" XPS IV

**Screenshots**

**Additional context**

**Comment by ehwarren** [comment]
Thank you! There is a bug open nothing some discrepancies but I haven't gone through to ensure all mappings are entirely correct. I'll tag this in that issue and work from there. 

#21
