### ISSUE TITLE
[BUG] DCF output incorrect, H2K file correct

### ISSUE THREAD

**Issue by liam-butters** [bluegrv/blue2k-issues#49]
**Describe the bug**
Blue2K DCF does not output the correct feature in ceiling

**To Reproduce**
Modelled a ceiling with R19 @ 5.5" batts as layer 1, and "same as layer 1" as layer 2.  Modelled crawl with EPS 2 @ 1.5".
Exported DCF from Blue2K
DCF PDF shows EPS_2_1_5 as the ceiling insulation.  This is incorrect, though this is the actual insulation in the crawl space.  The crawl space shows "EPS_1_0_75", which is also incorrect.
H2K file is correct, but Blue2K DCF is incorrect.

**Expected behavior**
Blue2K and the H2K file and the DCF should all match.

**Screenshots**

**Additional context**

**Comment by liam-butters** [comment]
Issue is present in walls, crawls, and ceilings.  Possibly more.

**Comment by ehwarren** [comment]
Fixed in 0.7.1
