### ISSUE TITLE
[BUG] Cannot export DCFs.  "Server side exception"

### ISSUE THREAD

**Issue by liam-butters** [bluegrv/blue2k-issues#51]
**Describe the bug**
Try to export DCF.  Get below noted error message

**To Reproduce**
1. Model file
2. Attempt to export DCF

**Expected behavior**
Should yield a PDF

**Screenshots**
![image](https://github.com/bluegrv/blue2k-issues/assets/139492023/13c4d875-98fc-4f10-841f-c2f02be11a95)

**Additional context**

**Comment by ehwarren** [comment]
fixed in 0.7.5
