### ISSUE TITLE
Authorization form template is an older version and does not include the AP # field[BUG]

### ISSUE THREAD

**Issue by liam-butters** [bluegrv/blue2k-issues#57]
**Describe the bug**
Looks like the NRCan authorization form that Blue2K populates is the old version without the AP # field.  The new version is attached.

**To Reproduce**
Populating the form works great.  but the content is not up to date.

**Expected behavior**

**Screenshots**
[7962D00_AuthorizationForm.pdf](https://github.com/bluegrv/blue2k-issues/files/13032727/7962D00_AuthorizationForm.pdf)

**Additional context**

**Comment by ehwarren** [comment]
New pdf form implemented in offline version.
